### ISSUE TITLE
Mobile wallet - "no trusted canonical hash trie"

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-blockchain#1028] opened 2020-05-05 03:20 UTC
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

We have started seeing a lot of `WARN [05-01|22:09:07.501] Served eth_getBlockByNumber              reqid=1685 t=276.406µs  err="no trusted canonical hash trie"` logs in the mobile wallet

### Steps to Reproduce Behavior

Run the wallet and look at the celo-blockchain logs

### Logs

`WARN [05-01|22:09:07.501] Served eth_getBlockByNumber              reqid=1685 t=276.406µs  err="no trusted canonical hash trie"`

### System information

Running @celo/client (npm package) built from commit `d2eca3f`

**Comment by kevjue** [comment] 2020-05-06 03:52
@lucasege and I did some investigation on this, and it appears that the root cause of why this is failing is that the light client is effectively creating a checkpoint after every 32k blocks, but that checkpoint is not correctly being created during the lightest sync.

@lucasege is currently figuring out the best way to deal with this (e.g. if we should remove it completely or some other alternative.

**Comment by mcortesi** [comment] 2020-11-06 00:42
Fixed on https://github.com/celo-org/celo-blockchain/pull/1031

**Closed by mcortesi** 2020-11-06 00:42 UTC
Labels: new
