### ISSUE TITLE
Failed to set randomness for proposer selection

### ISSUE THREAD

**Issue by mrsmkl** [celo-org/celo-blockchain#999] opened 2020-04-20 20:21 UTC
### Expected Behavior

If current block is epoch block like 207360, should it use the randomness of that block?
Edit: hmm nope, but the randomness is lost already?

### Current Behavior

Matt Harrop / Figment NetworkToday at 10:33 PM
Watching a new key / new validator start up after key rotation, and it did not go perfectly.
https://baklava-blockscout.celo-testnet.org/address/0xa254e52929a6a4a0e60c5ea5a0e3d89c7ee394da/signed
This is the new signer key.

See also:
https://github.com/celo-org/celo-monorepo/issues/2625
https://github.com/celo-org/celo-blockchain/issues/678

### Logs

```
ERROR[04-20|19:27:29.306] Error in calling the EVM                 funcName=getBlockRandomness                transactionData=0xfc4847260000000000000000000000000000000000000000000000000000000000032a00 err="evm: execution reverted"
ERROR[04-20|19:27:29.306] Error when invoking evm function         err="evm: execution reverted"       funcName=getBlockRandomness                static=true  address=0x2b3A515119695cEec51885c4E40cB5AF43265F3E args=[+207360] gas=2000000 gasLeft=1996896 value=<nil>
ERROR[04-20|19:27:29.306] Error in executing function on registered contract function=getBlockRandomness                registryId=0x02dfe2d0485b616b61db1800f30f4a14b26754b328fa09ba4ec73ee7276766cc err="evm: execution reverted"
WARN [04-20|19:27:29.306] Failed to set randomness for proposer selection block_number=224640 hash=c45e82…c9706c error="evm: execution reverted"
```

### System information

Run `geth version`

**Comment by nategraf** [comment] 2020-04-21 17:59
Root cause is https://github.com/celo-org/celo-monorepo/issues/3523

**Comment by kevjue** [comment] 2020-12-16 00:18
@mrsmkl  - I'm going to close this issue.  In the "Expected Behavior" section, you mention that the issue is retrieving the shuffled validator set ordering while the block being mined is the last block of an epoch.

It actually should work, since the randomness of the last block of the previous epoch is saved (https://github.com/celo-org/celo-monorepo/blob/12046fcd8adbea999fc94509717971eaebc9b4c3/packages/protocol/contracts/identity/Random.sol#L25) and retrieval-able, for the *current* use case of that variable.  Specifically, the validator will retrieve that variable to figure out the proposer for the consensus round of the mined last block, and then call addRandomness (https://github.com/celo-org/celo-monorepo/blob/12046fcd8adbea999fc94509717971eaebc9b4c3/packages/protocol/contracts/identity/Random.sol#L101), which will update that variable to be the mined block's random beacon's random value.

So there is a subtle bug in once `addRandomness` is called, then it's not possible to retrieve the previous epoch's last block.  I don't think this bug is causing issues for us now, so I'm going to close this one, and create one in celo-monorepo describing this subtle bug.

**Closed by kevjue** 2020-12-16 00:18 UTC
Labels: blockchain, dev-support
