### ISSUE TITLE
validator disconnects from proxy: useless peer

### ISSUE THREAD

**Issue by SlavaMo** [celo-org/celo-blockchain#1230] opened 2020-11-13 22:33 UTC
**Describe the bug**
Update 1.0.1 -> 1.1.1 gone not very smooth. 19 blocks downtime instead of 8-9-10 as reported by other validators.

My setup is: 2 dedicated servers in same DC, connected via private network and public network.

Updated proxy in 8 blocks.
Validator: `docker pull && docker stop old-container -t 60 && docker run` and then strange messages:

```
 INFO [11-13|21:36:53.895] Ethereum peer connected                  id=deb9355113895351 conn=staticdial name=celo/v1.1.1-stable/linux-amd64/go1.14.12
 INFO [11-13|21:37:03.252] Block synchronisation started 
 INFO [11-13|21:37:03.252] Stopping istanbul.Engine validating 
 INFO [11-13|21:37:03.252] Mining aborted due to sync 
 INFO [11-13|21:37:03.252] Disconnecting from static or trusted peer id=deb9355113895351 conn=staticdial purpose=ProxyPurpose reason="useless peer" remoteRequested=false err="useless peer"
 INFO [11-13|21:37:28.899] Ethereum peer connected                  id=deb9355113895351 conn=staticdial name=celo/v1.1.1-stable/linux-amd64/go1.14.12
 INFO [11-13|21:37:33.121] Disconnecting from static or trusted peer id=deb9355113895351 conn=staticdial purpose=ProxyPurpose reason="useless peer" remoteRequested=false err="useless peer"
 WARN [11-13|21:37:53.910] No proxy peers, cannot send Istanbul Validator Enodes Share message func=sendValEnodesShareMsg
```

**To Reproduce**
Not sure i am ready to experiment on my mainnet node to try reproducing this, just reporting in case somebody else spots same.
Full log: [validator-log.txt](https://github.com/celo-org/celo-blockchain/files/5539575/validator-log.txt)

Docker image
```
     "Image": "sha256:ff1ed14dfbd8d6c5bfd7e8dabe0be14082cc7f3e3f070cc4d077b046324083ec",
```

Validator start params:
```
docker run --name celo-validator -dit --restart unless-stopped -p 127.0.0.1:30303:30303 -p 127.0.0.1:30303:30303/udp -p 6060:6060 -v /root/celo-validator-node:/root/.celo us.gcr.io/celo-org/geth:1.1.1 --verbosity 3 --networkid 42220 --syncmode full --mine --istanbul.blockperiod=5 --istanbul.requesttimeout=3000 --etherbase 0x953f2501B18a3FdCF959aA901e74D5308e4D522f --nodiscover --nousb --proxy.proxied --proxy.proxyenodeurlpair=enode://36c30f8464987da3e4d2fd2a07c8e461e2fb410833edad0a5bb82d9606ac9c03351ff5686b9ec27f15619822defd186987b231a885aa36b05949cc7d0ccc1dbe@192.168.100.1:30503;enode://36c30f8464987da3e4d2fd2a07c8e461e2fb410833edad0a5bb82d9606ac9c03351ff5686b9ec27f15619822defd186987b231a885aa36b05949cc7d0ccc1dbe@95.217.113.102:30303 --unlock=0x953f2501B18a3FdCF959aA901e74D5308e4D522f --password /root/.celo/.password --pprof --pprofaddr 0.0.0.0 --pprofport 6060 --metrics --ethstats=SlavaMo@stats-server.celo.org
```

**Expected behavior**
no "useless peer" messages

**Comment by oneeman** [comment] 2021-01-06 16:31
#1283 takes care of the useless peer messages.  Though it does not fix the root cause of this issue, it fixes a problem in the error handling that was preventing us from seeing the underlying error behind this issue.  As such, we unfortunately can't further debug this issue and so I'm going to close it.  If it reoccurs in the futures on versions that include #1283, we'll be able to see the underlying error and hopefully identify the cause.

**Closed by oneeman** 2021-01-06 16:31 UTC
Labels: blockchain, dev-support
