### ISSUE TITLE
"Failed to set randomness for proposer selection" Error

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#678] opened 2019-12-02 14:16 UTC
### Expected Behavior

Sounds like a bug we should investigate

### Current Behavior

Getting this error on GETH, hundreds  of times
```
ERROR[11-29|15:04:27.218] Failed to set randomness for proposer selection block_number=15084 hash=ef10d7…f8ed2f error="missing trie node 0cb03e18722ca18910280402b65954c7be49d72bb85137916fe5e273c7be1756 (path )"
ERROR[11-29|15:04:27.223] Failed to set randomness for proposer selection block_number=15084 hash=ef10d7…f8ed2f error="missing trie node 0cb03e18722ca18910280402b65954c7be49d72bb85137916fe5e273c7be1756 (path )"
```

**Comment by nategraf** [comment] 2019-12-02 19:09
It's a bug if it happens when the network is live and stable, but not if it happens before the randomness contract is deployed or the node is not synced. However, if this node is trying to validate it cannot until this error is resolved, so in some cases this would be serious. This message could reasonably be downgraded to a warning or extra checks could be added around where it is produced.

**Comment by bonham000** [comment] 2020-01-22 08:36
I get a similar error when running the `celocli rewards:show` command, e.g.

```
Error: Returned error: missing trie node 4f4791adeb99aafcf633d2cde1d20736bee28696c9d99c0de17c72a46233b686 (path )
    at Object.ErrorResponse (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at ~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/src/utils/eth-debug-provider.ts:16:7)
    at XMLHttpRequest.request.onreadystatechange (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
    at XMLHttpRequestEventTarget.dispatchEvent (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
    at XMLHttpRequest._setReadyState (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:219:8)
    at XMLHttpRequest._onHttpResponseEnd (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:345:8)
    at IncomingMessage.<anonymous> (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/xhr2-cookies/xml-http-request.ts:311:39)
```

The command always fails with this error for me. I'm not sure if this is related to the issue here, I can open a new issue if this is a separate problem.

**Comment by nategraf** [comment] 2020-01-22 17:23
I believe this is a separate issue @bonham000 It seems like your node doesn't have the full EVM state, including history (which is needed for that command), although it's hard to tell why from here.

**Comment by nategraf** [comment] 2020-02-06 01:46
Based on recent investigation of what appears to be the same error. I believe this issue can be considered a duplicate of https://github.com/celo-org/celo-monorepo/issues/2625

**Comment by nategraf** [comment] 2020-04-21 00:14
Closing this issues as a duplicate of celo-org/celo-monorepo#2625

**Closed by nategraf** 2020-04-21 00:14 UTC
Labels: Priority: P2, betanet-phase-3, bug, protocol
