### ISSUE TITLE
Validator loses connection to all validators

### ISSUE THREAD

**Issue by tyrion70** [celo-org/celo-blockchain#1040] opened 2020-05-17 12:50 UTC
### Expected Behavior

Validator is connected to all other validators

### Current Behavior

Validator killed connection to all other validators

### Steps to Reproduce Behavior

I'm not sure, but these are the things I was trying before this happened.

Validator was missing signatures once in a while. To see if having more connections would have a positive effect I've been adding around 200 addTrustedNodes that I got from fullnodes. This increased the connections of the validator to round 300.

At 16:34 the validator lost all connections to specifically validators. In the logging I could see these lines repeated for almost all validators:
```May 16 16:34:20 prod-celo-validator1a geth[5649]: INFO [05-16|16:34:20.110] Disconnecting from static or trusted peer id=e1eea4fd60fe08f1 conn=trusted-staticdial static=ValidatorPurpose      trusted=ValidatorPurpose                        reason="useless peer"           remoteRequested=false err="useless peer"```

Here you can see the drop in connections around that time. Normal connections weren't killed.
<img width="508" alt="Screenshot 2020-05-17 at 14 35 24" src="https://user-images.githubusercontent.com/4341712/82147011-30643a00-984d-11ea-9ace-beef66d294ef.png">
<img width="505" alt="Screenshot 2020-05-17 at 14 35 33" src="https://user-images.githubusercontent.com/4341712/82147015-31956700-984d-11ea-99d6-803853e2d9b2.png">

As a result the validator lost 17 signatures

### Logs

These are the logs surrounding the event. Mind that these logs exclude loglines matching the following messages:

Deep froze chain segment
Processing istanbul backlog
Ethereum handshake failed
Commit new mining work
Imported new chain segment
Metered peer count reached the limit
too many peers
Error sending all version certificates

### System information

```
# geth version
Celo
Version: 1.0.0-stable
Git Commit: 8a44c2cd92200bdffce595c7558e84a39ea2bc15
Architecture: amd64
Protocol Versions: [65 64]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

running without docker with geth directly under systemctl

**Comment by tyrion70** [comment] 2020-05-17 12:51
[Discover 2020-05-16T14_30_00.000Z - 2020-05-16T15_00_00.000Z.csv.zip](https://github.com/celo-org/celo-blockchain/files/4640253/Discover.2020-05-16T14_30_00.000Z.-.2020-05-16T15_00_00.000Z.csv.zip)
The log file

**Comment by kevjue** [comment] 2020-05-18 22:47
@tyrion70 - Did you happen to see any of these logs:  https://github.com/celo-org/celo-blockchain/blob/master/eth/handler.go#L414?

**Comment by tyrion70** [comment] 2020-06-07 09:33
@kevjue they are not in the logfile I shared, and the message is Debug so don't think I've seen those no.

**Comment by oneeman** [comment] 2021-01-06 16:31
#1283 takes care of the useless peer messages.  Though it does not fix the root cause of this issue, it fixes a problem in the error handling that was preventing us from seeing the underlying error behind this issue.  As such, we unfortunately can't further debug this issue and so I'm going to close it.  If it reoccurs in the futures on versions that include #1283, we'll be able to see the underlying error and hopefully identify the cause.

**Closed by oneeman** 2021-01-06 16:31 UTC
Labels: blockchain, dev-support
