### ISSUE TITLE
Adapt "LightChain" to "lightest" sync mode

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#768] opened 2019-12-17 21:50 UTC
Some functions in "LightChain" need to be adapted to cover the assumptions in "lightest" mode (e.g. we don' t have all headers)

Alternatively, a "LightestChain" object would work.

**Comment by kevjue** [comment] 2020-04-28 23:39
Dupe of https://github.com/celo-org/celo-blockchain/issues/1011

**Closed by kevjue** 2020-04-28 23:39 UTC
Labels: Priority: P1, bug, celo-blockchain
