### ISSUE TITLE
Memory leak on full nodes and validators

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-blockchain#532] opened 2019-10-16 19:10 UTC
### Expected Behavior

Memory usage by tx-nodes and validators remains constant

### Current Behavior

There seems to be a memory leak that's being seen on validators and tx-nodes (though not as extreme).

Example validator:

![Screen Shot 2019-10-16 at 12 02 26 PM](https://user-images.githubusercontent.com/20362969/66950604-8f3ea800-f00d-11e9-8aef-ba11c67daa0f.png)

Example tx-node:

![Screen Shot 2019-10-16 at 12 02 06 PM](https://user-images.githubusercontent.com/20362969/66950626-982f7980-f00d-11e9-8cd0-ff05ebdbb612.png)

Here's a `pprof` rendering from a tx-node:

![out](https://user-images.githubusercontent.com/20362969/66950652-a9788600-f00d-11e9-9ee9-f4f9fe4565cc.png)

I wasn't able to find anything super conclusive, just that levelDB looked suspicious. Planning on running my own testnet with `--pprof` and seeing if there is anything noticeable

**Comment by mattharrop** [comment] 2019-10-18 23:25
My validator node consistently crashes after a few hours running on an instance with 8gb RAM.  Logs from the crash attached.
[celocrash.log](https://github.com/celo-org/celo-blockchain/files/3745937/celocrash.log)

**Comment by tkporter** [comment] 2019-10-22 18:56
Looks like discv5 is the one to blame:

![Screen Shot 2019-10-22 at 11 39 38 AM](https://user-images.githubusercontent.com/20362969/67320251-d07a0080-f4c2-11e9-81c2-aaeddee25652.png)

![Screen Shot 2019-10-22 at 11 45 25 AM](https://user-images.githubusercontent.com/20362969/67320264-d5d74b00-f4c2-11e9-9fa5-5d4d660d04d9.png)

(Note it doesn't seem like the sum of all the entries comes out to 631 MB, so there must be some inaccuracy here ^)

**Comment by daithi-coombes** [comment] 2019-12-02 00:12
This issue is very very similar: https://github.com/ethereum/go-ethereum/issues/16859
 and should've been fixed in: https://github.com/ethereum/go-ethereum/pull/16880

from @mattharrop logs above, there's plenty of goroutines hanging for 2hrs
```
 goroutine 1 [chan receive, 160 minutes]:
```

Also in network logs there's false positives about bad enode urls:
```
Error in upserting a valenode entry      AnnounceMsg="{Address: 0x132EA61AaE41
A3beE6a2faf45aAE68e2A7f9457F, View: {Round: 0, Sequence: 496530}, IncompleteEnodeURL: enode://c8f8bc50da
1780163761d738a1cbed328df7b82900e9d7ada38fb505fe589af60982b91e9b950a75bf677fabaafdf409fe9d2c0f9ead523946
70ed5f1da7f5eb, Signature: f3d205bd4a570b95671c9afba818d73b27cb62fb21376c7a184354b7f9e4745f3d65d4b8aabee
3621abe115ac099539037949771e4d6497dd72ac6ffe351d83001}" error="old announce message"
```
(am basing false positive on `error="old announce message")

am thinking dangling requests in discovery are the cause, for now. Will post `heapdump` as per this instructions: https://github.com/celo-org/celo-blockchain/issues/573#issuecomment-556250251

**Comment by trianglesphere** [comment] 2020-12-03 22:01
Closing because it seems like issue #1197 is the same, except with newer logs.

**Closed by trianglesphere** 2020-12-03 22:01 UTC
Labels: blockchain
