### ISSUE TITLE
missing signatures form a visible pattern in validator:signed-blocks

### ISSUE THREAD

**Issue by SlavaMo** [celo-org/celo-blockchain#1009] opened 2020-04-25 20:22 UTC
EDIT: missing signatures were forming a visible pattern but now started to disappear.

### Current Behavior
Missing signatures form a pattern which is visible with `celocli validator:signed-blocks --signer 0x42d441b6793e6162b979fbf6ad0af0063cbec96a --lookback=10000`:
  44800 ........................................
  44840 ...............✘........................
  44880 ......................................✘.
  44920 ........................................
  44960 .....................✘..................
  45000 ........................................
  45040 ....✘...................................
  45080 ...........................✘............
  45120 ........................................
  45160 ..........✘.............................
  45200 .................................✘......
  45240 ........................................
  45280 ........................................
  45320 .......................................✘
  45360 ........................................
  45400 ......................✘.................
  45440 ........................................
  45480 .....✘..................................
  45520 ............................✘...........
  45560 ........................................
  45600 ...........✘............................
  45640 ..................................✘.....
  45680 ........................................
  45720 .................✘......................
  45760 ........................................
  45800 ✘.......................................
  45840 .......................✘................
  45880 ........................................
  45920 ......✘.................................
  45960 .............................✘..........
  46000 ........................................
  46040 ........................................
  46080 ......................✘............✘....
  46120 ........................................
  46160 ..................✘.....................
  46200 ........................................
  46240 .✘......................................
  46280 ........................✘...............
  46320 ........................................
  46360 .......✘................................
  46400 ..............................✘.........
  46440 ........................................
  46480 .............✘..........................

also i have checked other validators at found that i'm not alone with this problem - heere is the list of missing signatures that look like mine: https://gist.github.com/SlavaMo/27737769ef5e42ddbdd395da9155ba6c

### Steps to Reproduce Behavior

dont know

### Logs
validator around block 45487 which is ✘ and is downtime:
```
 INFO [04-25|07:44:22.500] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45484 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:44:27.024] Commit new mining work                   number=45484 sealhash=186ea0…248a2c txs=0  gas=0      fees=0            elapsed=4.595s
 INFO [04-25|07:44:27.393] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.870ms  mgasps=0.000  number=45484 hash=283bfa…b524e7 dirty=1.28MiB
 INFO [04-25|07:44:27.404] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=283bfa…b524e7 number=45484
 INFO [04-25|07:44:27.405] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc010a1b4a0 transactions:[
 INFO [04-25|07:44:27.501] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45485 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:44:32.022] Commit new mining work                   number=45485 sealhash=875d4a…340b54 txs=0  gas=0      fees=0            elapsed=4.629s
 INFO [04-25|07:44:32.461] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=b8a1bc…80472b number=45485
 INFO [04-25|07:44:32.461] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc0111ad860 transactions:[
 INFO [04-25|07:44:32.486] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.587ms  mgasps=0.000  number=45485 hash=b8a1bc…80472b dirty=1.28MiB
 INFO [04-25|07:44:32.543] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45486 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:44:37.022] Commit new mining work                   number=45486 sealhash=a83e5f…05dfd6 txs=0  gas=0      fees=0            elapsed=4.536s
 INFO [04-25|07:44:37.410] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=69cb07…287e10 number=45486
 INFO [04-25|07:44:37.410] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc011973680 transactions:[
 INFO [04-25|07:44:37.438] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.562ms  mgasps=0.000  number=45486 hash=69cb07…287e10 dirty=1.28MiB
*INFO [04-25|07:44:37.491] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45487 cur_epoch=3 cur_round=0  des_rou
*INFO [04-25|07:44:42.022] Commit new mining work                   number=45487 sealhash=3e28a9…adbcef txs=0  gas=0      fees=0            elapsed=4.583s
*INFO [04-25|07:44:42.078] Processing istanbul backlog              type=MsgBacklog   func=processBacklog               cur_seq=45487 cur_round=0  considered=4  future=0 enqueued=4
*INFO [04-25|07:44:42.422] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=46503a…eeee08 number=45487
*INFO [04-25|07:44:42.422] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc0158874a0 transactions:[
*INFO [04-25|07:44:42.445] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.598ms  mgasps=0.000  number=45487 hash=46503a…eeee08 dirty=1.28MiB
 INFO [04-25|07:44:42.517] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45488 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:44:47.024] Commit new mining work                   number=45488 sealhash=288f75…93a6d6 txs=0  gas=0      fees=0            elapsed=4.578s
 INFO [04-25|07:44:47.418] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=f8df19…a53b32 number=45488
 INFO [04-25|07:44:47.418] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc0086d3c20 transactions:[
 INFO [04-25|07:44:47.449] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=15.770ms  mgasps=0.000  number=45488 hash=f8df19…a53b32 dirty=1.28MiB
 INFO [04-25|07:44:47.510] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45489 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:44:52.022] Commit new mining work                   number=45489 sealhash=bed05a…6e3fce txs=0  gas=0      fees=0            elapsed=4.573s
 INFO [04-25|07:44:52.423] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=b416e7…b66e07 number=45489
 INFO [04-25|07:44:52.423] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc015716000 transactions:[
 INFO [04-25|07:44:52.449] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.794ms  mgasps=0.000  number=45489 hash=b416e7…b66e07 dirty=1.28MiB
 INFO [04-25|07:44:52.518] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45490 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:44:53.899] encrypting enodeURL                      func=generateEncryptedEnodeURLs   enodeURL=enode://36c30f8464987da3e4d2fd2a07c8e461e2fb410833edad0a5bb82d9606ac9c03351ff5686b9ec27f
 INFO [04-25|07:44:57.022] Commit new mining work                   number=45490 sealhash=800998…3bd9a3 txs=0  gas=0      fees=0            elapsed=4.573s
 INFO [04-25|07:44:57.461] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=4a8b20…27fd12 number=45490
 INFO [04-25|07:44:57.461] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc011585860 transactions:[
 INFO [04-25|07:44:57.485] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.552ms  mgasps=0.000  number=45490 hash=4a8b20…27fd12 dirty=1.28MiB
 INFO [04-25|07:44:57.547] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45491 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:45:02.024] Commit new mining work                   number=45491 sealhash=35a09e…3f21fc txs=0  gas=0      fees=0            elapsed=4.539s
 INFO [04-25|07:45:02.400] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=d212f0…4f0df1 number=45491
 INFO [04-25|07:45:02.400] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc010d9ed20 transactions:[
 INFO [04-25|07:45:02.431] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=17.102ms  mgasps=0.000  number=45491 hash=d212f0…4f0df1 dirty=1.28MiB
 INFO [04-25|07:45:02.503] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45492 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:45:07.022] Commit new mining work                   number=45492 sealhash=ff7ea9…7e79ca txs=0  gas=0      fees=0            elapsed=4.590s
 INFO [04-25|07:45:07.456] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=02d38c…b9f49e number=45492
 INFO [04-25|07:45:07.456] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc01026a000 transactions:[
 INFO [04-25|07:45:07.483] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.637ms  mgasps=0.000  number=45492 hash=02d38c…b9f49e dirty=1.28MiB
 INFO [04-25|07:45:07.557] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45493 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:45:12.023] Commit new mining work                   number=45493 sealhash=58a4af…a83d8d txs=0  gas=0      fees=0            elapsed=4.539s
 INFO [04-25|07:45:12.411] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A round=0 hash=885f29…77ca4d number=45493
 INFO [04-25|07:45:12.411] Committed                                address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=commit                       proposal="&{header:0xc0115f3680 transactions:[
 INFO [04-25|07:45:12.437] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.732ms  mgasps=0.000  number=45493 hash=885f29…77ca4d dirty=1.28MiB
 INFO [04-25|07:45:12.508] Error in handling istanbul message       address=0x42d441B6793E6162B979fBF6ad0aF0063CBec96A func=handleEvents                 cur_seq=45494 cur_epoch=3 cur_round=0  des_rou
 INFO [04-25|07:45:17.024] Commit new mining work                   number=45494 sealhash=bb3f66…590ef4 txs=0  gas=0      fees=0            elapsed=4.586s
 INFO [04-25|07:45:17.050] Processing istanbul backlog              type=MsgBacklog   func=processBacklog               cur_seq=45494 cur_round=0  considered=1  future=0 enqueued=1
 INFO [04-25|07:45:17.412] Imported new chain segment               blocks=1  txs=0  mgas=0.000 elapsed=10.642ms  mgasps=0.000  number=45494 hash=772d06…15f93a dirty=1.28MiB
```
proxy around the same block:

```
 INFO [04-25|07:44:35.031] Ethereum peer connected                  id=c6b836370d9a22fc conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:35.520] Ethereum peer connected                  id=6d0bbbcefde37db2 conn=trusted-inbound    name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:35.548] Ethereum peer connected                  id=3f4b4347b14de07d conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:35.556] Ethereum peer connected                  id=ba30d3d2f7e57710 conn=trusted-staticdial name=celo/v1.0.0-stable-8a44c2cd/linux-amd64/go1.13.8
 INFO [04-25|07:44:35.573] Disconnecting from static or trusted peer id=3f4b4347b14de07d conn=trusted-staticdial static=ValidatorPurpose trusted=ValidatorPurpose reason="already connected" remoteRequ
 INFO [04-25|07:44:35.573] Ethereum handshake failed                id=3f4b4347b14de07d conn=trusted-staticdial err=EOF
 INFO [04-25|07:44:35.584] Ethereum peer connected                  id=185ad8fd84a68115 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:35.588] Ethereum peer connected                  id=83509a9789e8bc8c conn=trusted-staticdial name=celo/v1.0.0-stable-8a44c2cd/linux-amd64/go1.13.8
 INFO [04-25|07:44:35.701] Ethereum peer connected                  id=c84bbb6439a46556 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.085] Ethereum peer connected                  id=c8e49a9ea8ebc65a conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.140] Ethereum peer connected                  id=06689e1efc58cc32 conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.205] Ethereum peer connected                  id=9877e908c14595f6 conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.511] Ethereum peer connected                  id=10af050e81755fd3 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.566] Ethereum peer connected                  id=3e1487fc9d574d31 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.608] Ethereum peer connected                  id=dfcd5902bca43d8f conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.647] Ethereum peer connected                  id=c56e1a9af08efc5a conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.647] Ethereum peer connected                  id=770657ab97680542 conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.654] Ethereum peer connected                  id=25be84e3ebc6287f conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.790] Ethereum peer connected                  id=4996939b43c0d677 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.814] Ethereum peer connected                  id=1ecce56e56d8072d conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.822] Ethereum peer connected                  id=269d9f0a6cfa5d12 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.850] Ethereum peer connected                  id=6ef0e14c5f9a2af4 conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.865] Ethereum peer connected                  id=f6417db45bab87e1 conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.876] Ethereum peer connected                  id=78f433ea75ce0f22 conn=trusted-staticdial name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:36.898] Ethereum peer connected                  id=b3453aa34e95afbd conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:37.157] Ethereum peer connected                  id=1f85713f5ff51a98 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:37.422] Imported new chain segment               blocks=1 txs=0  mgas=0.000 elapsed=10.440ms mgasps=0.000  number=45486 hash=69cb07…287e10 dirty=1.28MiB
 INFO [04-25|07:44:40.070] Ethereum peer connected                  id=13c103780829f195 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.122] Ethereum peer connected                  id=88248e6e1747a9ce conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.396] Ethereum peer connected                  id=00da63181e2aaaa2 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.398] Ethereum peer connected                  id=269d9f0a6cfa5d12 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.402] Ethereum peer connected                  id=6bfb62329aca61cd conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.498] Ethereum peer connected                  id=799b8b48b6be2b8a conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.500] Ethereum peer connected                  id=2b504ea638b4b15b conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.517] Ethereum peer connected                  id=0da620d41c0190c0 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.534] Ethereum peer connected                  id=09ffb5046c31b077 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.684] Ethereum peer connected                  id=4b150f9b5df38079 conn=dyndial            name=celo/v1.0.0-stable-8a44c2cd/linux-amd64/go1.13.8
 INFO [04-25|07:44:40.685] Ethereum peer connected                  id=66dee21c169a210b conn=dyndial            name=celo/v1.0.0-stable-8a44c2cd/linux-amd64/go1.13.8
 INFO [04-25|07:44:40.725] Ethereum peer connected                  id=36dc4a88f449c720 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.743] Ethereum peer connected                  id=1279c461707c8ef9 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.749] Ethereum peer connected                  id=185ad8fd84a68115 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.847] Ethereum peer connected                  id=70c4d80bd6a32d62 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:40.892] Ethereum peer connected                  id=00ddbef60698a78a conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
*INFO [04-25|07:44:42.413] Imported new chain segment               blocks=1 txs=0  mgas=0.000 elapsed=10.551ms mgasps=0.000  number=45487 hash=46503a…eeee08 dirty=1.28MiB
 INFO [04-25|07:44:43.026] Ethereum peer connected                  id=17a01cf603f462d9 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:43.175] Ethereum peer connected                  id=0bb97bf72f3750de conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:43.729] Ethereum peer connected                  id=30cc5e5ed0839da7 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:44.039] Ethereum peer connected                  id=490fe716268d4100 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:44.134] Ethereum peer connected                  id=10af050e81755fd3 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:44.185] Ethereum peer connected                  id=34c7aa8280323511 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:44.534] Ethereum peer connected                  id=71c4fbd9b59159c0 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:45.918] Ethereum peer connected                  id=d90c9ff839b5a860 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:46.052] Ethereum peer connected                  id=87b69ac8c9434bd4 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:46.424] Ethereum peer connected                  id=d8761da5982e23a4 conn=dyndial            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:46.425] Ethereum peer connected                  id=01c99d371e374038 conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:46.740] Ethereum peer connected                  id=3bed805412d7c943 conn=inbound            name=celo/v1.0.0-unstable-09e4037e-20200422/linux-amd64/go1.13.10
 INFO [04-25|07:44:46.979] Ethereum peer connected                  id=2b504ea638b4b15b conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:47.212] Ethereum peer connected                  id=799b8b48b6be2b8a conn=inbound            name=celo/v1.0.0-stable/linux-amd64/go1.13.10
 INFO [04-25|07:44:47.390] Imported new chain segment               blocks=1 txs=0  mgas=0.000 elapsed=10.581ms mgasps=0.000  number=45488 hash=f8df19…a53b32 dirty=1.28MiB
```

### System information

Celo
Version: 1.0.0-stable
Architecture: amd64
Protocol Versions: [65 64]
Go Version: go1.13.10
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

**Comment by SlavaMo** [comment] 2020-04-25 20:23
now things are getting better. notice how it was rising steadily:
![image](https://user-images.githubusercontent.com/56453863/80290066-aba16700-874b-11ea-82af-9f76fd8edd8f.png)

**Comment by SlavaMo** [comment] 2020-04-25 20:26
also notice how much downtime is in this block comparing to other blocks around: https://explorer.celo.org/blocks/45487/signers

**Comment by SlavaMo** [comment] 2020-04-25 20:35
still some of the signers look very weird:
0x7eEC94733d16B96C6fE877464630BB5Be1E5c3f2:
![image](https://user-images.githubusercontent.com/56453863/80290309-2fa81e80-874d-11ea-8a4e-312ee60ffa82.png)

0xF139e74aDEC329E715AB49a68c5548A00e40CBc2:
![image](https://user-images.githubusercontent.com/56453863/80290386-5a927280-874d-11ea-8667-08c404e74356.png)

**Comment by SlavaMo** [comment] 2020-05-15 12:24
https://drive.google.com/drive/folders/1Wu_cLCEEM8Sty5kgGOX7yPYD_-nIPTg2?usp=sharing

it is a log of validator SlavaMo (signer=[0x42d441b6793e6162b979fbf6ad0af0063cbec96a](https://explorer.celo.org/address/0x42d441b6793e6162b979fbf6ad0af0063cbec96a/signed)) for last 3 hours with `debug.vmodule("consensus/istanbul/*=5")`

currently my signatures look like this:
![image](https://user-images.githubusercontent.com/56453863/82050011-0c272280-96c0-11ea-8d8d-6336f6678484.png)

**Comment by haferman** [comment] 2020-05-19 00:22
Any possibility that this is related to
https://github.com/celo-org/celo-blockchain/issues/808 ?

**Comment by Bijan-Massoumi** [comment] 2020-05-21 22:09
I just hit this issue around 14:00 UTC

<img width="803" alt="image" src="https://user-images.githubusercontent.com/7463982/82611265-feb4e100-9b74-11ea-990c-892959cd1360.png">

**Comment by nategraf** [comment] 2020-12-15 20:38
I don't see any information in the logs provided here that can help us find the exact issue, but I can provide some more information about the general pattern we are seeing here.

In each of the cases provided, there is periodic nature to the missed signatures. It's generally the case that the period of the pattern (i.e. how many blocks there are between repetitions) is equal to the number of online and elected validator signers. If this is the case, the issue is related to one or more particular peer validators. When those validators propose a block, the down validator is not signing it.

**The most common reason that a a validator is not signing blocks proposed by a particular peer is that they are not connected**. When two validators are not connected, they cannot exchange proposals or signatures, and so any block proposed by one will not reach the other, which prevents the non-proposer from signing the block.

When this is the case, it is also common to see that a signature is missing from the non-proposer for the block before the one proposed by the disconnected peer, as is the case in the image shared by @Bijan-Massoumi and in the second set of images shared by @SlavMo. This is because the proposer assembles the parent seal on the block, which is used for the official record of who signed a particular block, and the proposer never received a signature from the non-proposer directly. It is possible for the proposer to receive the signature indirectly, which is why the previous block is not _always_ have a missing signature, but generally the signature from the non-proposer will not appear in the parent seal.

Some additional examples of this come from discussion Discord, such as [this one on June 26](https://discord.com/channels/600834479145353243/601046166620078100/726177917209673759) or [this one on July 18](https://discord.com/channels/600834479145353243/601046166620078100/734117887123521647)

It's also possible for other issues, unrelated to the network connections, to cause the same behavior. In theory, if there was a bug that caused blocks proposed by a particular validator to be rejected by a particular peer, the same pattern would appear. We do not currently know of any issue that would cause this. The `Error in handling istanbul message` seen in the logs of the issue description indicate that something may be happening that that effect, but unfortunately the actual error message is cut off and the rest of the logs look normal, so there isn't enough information here to dig further.

I am going to close this issue right now as there is not action we can take without additional information, and it's been quite a while since it was opened. If more information is available, please reopen this issues and tag me. I'll be happy to look into it further.

**Closed by nategraf** 2020-12-15 20:38 UTC
Labels: blockchain, dev-support

**Comment by nategraf** [comment] 2020-12-15 22:42
Here is a common cause for patterns like this https://github.com/celo-org/celo-blockchain/issues/1088
