### ISSUE TITLE
Ultralight clients should not import block headers from all peers

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-blockchain#805] opened 2020-01-10 01:09 UTC
### Expected Behavior

It should be more intelligent about who to request block headers from. 1 is probably too little, but all is too many

### Current Behavior

It seems like an ultralight client will import blockheaders from all its peers:

### Steps to Reproduce Behavior

Run an ultralight client

### Logs

```
INFO [01-10|00:52:35.165] Block synchronisation started 
INFO [01-10|00:52:41.438] Imported new block headers               count=192 elapsed=1.853s number=138240 hash=e12e5a…ed2689 age=2mo1w1d
INFO [01-10|00:52:41.440] Upgrading chain index                    type=bloombits percentage=0
INFO [01-10|00:52:41.441] Upgrading chain index                    type=cht       percentage=0
INFO [01-10|00:52:41.751] Finished upgrading chain index           type=cht
INFO [01-10|00:52:41.757] Finished upgrading chain index           type=bloombits
INFO [01-10|00:52:43.480] Imported new block headers               count=192 elapsed=2.025s number=276480 hash=225738…48c3bb age=2mo3h54m
INFO [01-10|00:52:45.483] Imported new block headers               count=192 elapsed=1.984s number=414720 hash=1371da…b2ef2a age=1mo3w13h
INFO [01-10|00:52:47.479] Imported new block headers               count=192 elapsed=1.979s number=552960 hash=bb082a…bd0721 age=1mo1w5d
INFO [01-10|00:52:49.454] Imported new block headers               count=192 elapsed=1.959s number=691200 hash=5dead2…9132f1 age=1mo4d30m
INFO [01-10|00:52:49.456] Upgrading chain index                    type=bloombits percentage=76
INFO [01-10|00:52:49.456] Upgrading chain index                    type=cht       percentage=76
INFO [01-10|00:52:49.864] Finished upgrading chain index           type=cht
INFO [01-10|00:52:49.877] Finished upgrading chain index           type=bloombits
INFO [01-10|00:52:51.430] Imported new block headers               count=192 elapsed=1.961s number=829440 hash=920f4f…8a03a7 age=3w3d21h
INFO [01-10|00:52:53.366] Imported new block headers               count=192 elapsed=1.955s number=967680 hash=e8d610…3c2f12 age=2w1d19h
INFO [01-10|00:52:55.353] Imported new block headers               count=192 elapsed=1.967s number=1105920 hash=f63c40…71921f age=6d17h7m
INFO [01-10|00:52:56.810] Imported new block headers               count=140 elapsed=1.441s number=1206720 hash=ab63b7…d3d11c age=1h5m41s
INFO [01-10|00:52:56.844] Imported new block headers               count=2   elapsed=20.036ms number=1207381 hash=f23f53…72eca0
INFO [01-10|00:52:57.011] Imported new block headers               count=1   elapsed=9.653ms  number=1207382 hash=c5fbb6…cf7a41
INFO [01-10|00:53:22.770] Imported new block headers               count=1   elapsed=9.662ms  number=1207383 hash=d361b0…008e8a
INFO [01-10|00:53:22.819] Imported new block headers               count=0   elapsed=9.623ms  number=1207383 hash=d361b0…008e8a ignored=1
INFO [01-10|00:53:22.862] Imported new block headers               count=0   elapsed=10.240ms number=1207383 hash=d361b0…008e8a ignored=1
INFO [01-10|00:53:22.882] Imported new block headers               count=0   elapsed=8.182ms  number=1207383 hash=d361b0…008e8a ignored=1
INFO [01-10|00:53:22.903] Imported new block headers               count=0   elapsed=8.013ms  number=1207383 hash=d361b0…008e8a ignored=1
INFO [01-10|00:53:22.924] Imported new block headers               count=0   elapsed=8.826ms  number=1207383 hash=d361b0…008e8a ignored=1
INFO [01-10|00:53:22.944] Imported new block headers               count=0   elapsed=8.039ms  number=1207383 hash=d361b0…008e8a ignored=1
INFO [01-10|00:53:22.965] Imported new block headers               count=0   elapsed=8.010ms  number=1207383 hash=d361b0…008e8a ignored=1
INFO [01-10|00:53:22.985] Imported new block headers               count=0   elapsed=8.315ms  number=1207383 hash=d361b0…008e8a ignored=1
INFO [01-10|00:53:23.634] Imported new block headers               count=1   elapsed=10.754ms number=1207384 hash=4bdcfb…44025a
```

### System information

Run `geth version`

**Comment by hbandura** [comment] 2020-12-03 23:58
@nambrot I know this is old, but I can't seem to reproduce this with the current code

**Comment by hbandura** [comment] 2020-12-04 00:03
I'll close this since it seems it does not happen anymore

**Closed by hbandura** 2020-12-04 00:03 UTC
Labels: blockchain
