### ISSUE TITLE
Head headers broke chain ordering 

### ISSUE THREAD

**Issue by mrsmkl** [celo-org/celo-blockchain#992] opened 2020-04-15 09:43 UTC
### Expected Behavior

Perhaps validator should never drop its proxy peer?

### Current Behavior

From y3v63n | moonli.me
```
WARN [04-15|00:11:37.221] Head headers broke chain ordering        peer=290790d1b3f31fad index=0 requested=125064 received=125068
WARN [04-15|00:11:37.221] Synchronisation failed, dropping peer    peer=290790d1b3f31fad err="retrieved hash chain is invalid"
INFO [04-15|00:11:37.221] Disconnecting from static or trusted peer id=290790d1b3f31fad conn=staticdial static=ProxyPurpose trusted= reason="useless peer"    remoteRequested=false err="useless peer"
```
After it, my validator missed a bunch of blocks

This error is emitted in function `findAncestor`. For some reason it got a message with wrong block headers. Perhaps the `BlockHeadersMsg` messages were mixed up somehow (there isn't any mechanism to match messages to replies?).

### Logs

Validator: https://pastebin.com/yMHHPuCA
Proxy: https://pastebin.com/raw/m56G7MH9

**Comment by nategraf** [comment] 2020-12-15 19:41
Looking at the proxy logs I see that the proxy was having network trouble and lost connection with many of its peers at once:
```
INFO [04-15|00:11:37.117] Disconnecting from static or trusted peer id=7c854e0859df49d8 conn=trusted-inbound    static=ValidatorPurpose trusted=ValidatorPurpose reason="network error"     remoteRequested=false err="read tcp 172.17.0.2:30303->116.202.157.121:57338: i/o timeout"
INFO [04-15|00:11:37.122] Disconnecting from static or trusted peer id=f0ecba655cf0b9ea conn=trusted-staticdial static=ValidatorPurpose trusted=ValidatorPurpose reason="network error"     remoteRequested=false err="read tcp 172.17.0.2:57452->116.202.156.45:30303: i/o timeout"
INFO [04-15|00:11:37.122] Disconnecting from static or trusted peer id=1532000210368f6b conn=trusted-inbound    static=ValidatorPurpose trusted=ValidatorPurpose reason="network error"     remoteRequested=false err="read tcp 172.17.0.2:30303->3.17.158.54:47044: i/o timeout"
INFO [04-15|00:11:37.123] Disconnecting from static or trusted peer id=297f7ef4c68097ac conn=trusted-inbound    static=ValidatorPurpose trusted=ValidatorPurpose reason="network error"     remoteRequested=false err="read tcp 172.17.0.2:30303->46.4.80.114:45174: i/o timeout"
INFO [04-15|00:11:37.124] Disconnecting from static or trusted peer id=940af4fa3b3c1303 conn=trusted-inbound    static=ValidatorPurpose trusted=ValidatorPurpose reason="network error"     remoteRequested=false err="read tcp 172.17.0.2:30303->35.233.244.5:35094: i/o timeout"
INFO [04-15|00:11:37.137] Disconnecting from static or trusted peer id=067f97058edcf700 conn=trusted-inbound    static=ValidatorPurpose trusted=ValidatorPurpose reason="network error"     remoteRequested=false err="read tcp 172.17.0.2:30303->62.171.148.56:48282: i/o timeout"
INFO [04-15|00:11:37.147] Disconnecting from static or trusted peer id=023a72a7e954817b conn=trusted-inbound    static=ValidatorPurpose trusted=ValidatorPurpose reason="network error"     remoteRequested=false err="read tcp 172.17.0.2:30303->80.64.208.28:37006: i/o timeout"
```
About 100ms after the proxy recognized that it had lost connection with its validator, connection was reestablished. Within 5s, the validator managed to download the missing blocks and restore sync to head.

In this incident it is most likely the case that the missed blocks were produced by the network in the time between the proxy losing connection to the validator and recognizing that the connection was lost. Some evidence for this is the the validator downloaded 6 blocks upon reestablishing connection, which indicates that it was about 30s behind, which also matches a typical network timeout.

With that in mind, the `headers broke chain ordering` message is likely an effect of the network trouble between the valdiator and the proxy, where the proxy sent multiple messages about new blocks and they were received out of order or one in the middle was missing.

On the suggestion of never dropping the proxy peer, I think that would be difficult and risky to implement. Dropping and reconnecting to the proxy provides a chance to "reset" any connection that that has gone bad due to network errors or other bugs. Removing this reset mechanism may open the door for more persistent issues. Additionally, In this case the reconnection happened quickly once the issue was recognized, which indicates the upside to preventing the proxy from being dropped would be limited.

My interpretation is that the blockchain client worked as intended under the circumstances (i.e. that the missed signatures were the result of a network error which could not have been avoided in the current configuration), and I am going to close this issue for now.

**Closed by nategraf** 2020-12-15 19:41 UTC
Labels: blockchain, dev-support
