### ISSUE TITLE
Precompile to detect double signing

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#637] opened 2019-11-23 03:02 UTC
### Expected Behavior

We have a precompile that takes two RLP encoded blocks and decodes them. If the block numbers are the same, return the intersection of the validator signer addresses. If the block numbers are different, or if the block hashes are the same, return the empty list.

### Current Behavior

No such precompile

**Comment by nategraf** [comment] 2020-02-06 01:47
Duplicate of closed issue https://github.com/celo-org/celo-blockchain/issues/696

**Closed by nategraf** 2020-02-06 01:47 UTC
