### ISSUE TITLE
Docker: Segmentation Fault on Attestation Node

### ISSUE THREAD

**Issue by joesixpack** [celo-org/celo-blockchain#984] opened 2020-04-11 04:57 UTC
### Expected Behavior

Attestation node should launch normally without errors as the other nodes do.

### Current Behavior

Crashing on launch.

### Steps to Reproduce Behavior
```
export CELO_IMAGE=us.gcr.io/celo-testnet/celo-node:baklava
export NETWORK_ID=200110
export BOOTNODE_ENODES=`docker run --rm --entrypoint cat $CELO_IMAGE /celo/bootnodes`

docker run --name celo-attestations -d --restart always -p 127.0.0.1:8545:8545 -p 30403:30303 -p 30403:30303/udp -v $PWD:/root/.celo $CELO_IMAGE --verbosity 3 --networkid $NETWORK_ID --syncmode full --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3,debug,admin --unlock $CELO_ATTESTATION_SIGNER_ADDRESS --password /root/.celo/.password --bootnodes $BOOTNODE_ENODES --nousb --allow-insecure-unlock
```
### Logs
```
stty: standard input: Not a tty
INFO [04-11|04:53:24.837] Maximum peer count                       ETH=175 LES=0 total=175
INFO [04-11|04:53:24.839] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [04-11|04:53:24.844] Starting peer-to-peer node               instance=celo/v0.10.0-stable/linux-amd64/go1.13.9
INFO [04-11|04:53:24.844] Allocated trie memory caches             clean=256.00MiB dirty=256.00MiB
INFO [04-11|04:53:24.845] Allocated cache and file handles         database=/root/.celo/celo/chaindata cache=768.00MiB handles=524288
INFO [04-11|04:53:24.869] Opened ancient database                  database=/root/.celo/celo/chaindata/ancient
ERROR[04-11|04:53:24.872] Invalid block header RLP                 hash=09deb5…b11180 err="rlp: input string too long for common.Address, decoding into (types.Header).Coinbase"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x34 pc=0xacc873]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/core.SetupGenesisBlockWithOverride(0x189eb40, 0xc0001d0380, 0x0, 0x0, 0x80000, 0x0, 0x0, 0x0, 0x0, 0x189eb40, ...)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/core/genesis.go:178 +0x493
github.com/ethereum/go-ethereum/eth.New(0xc0001522d0, 0xc0002a4000, 0x156f020, 0xc00053f7d0, 0x41a308)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/backend.go:146 +0x333
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService.func2(0xc0001522d0, 0xc0001521e0, 0xc00053f9b8, 0xc0002de560, 0x2)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1671 +0x3d
github.com/ethereum/go-ethereum/node.(*Node).Start(0xc0000ce800, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/node/node.go:232 +0x741
github.com/ethereum/go-ethereum/cmd/utils.StartNode(0xc0000ce800)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/cmd.go:67 +0x2f
main.startNode(0xc0000e4000, 0xc0000ce800)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:322 +0x70
main.geth(0xc0000e4000, 0x0, 0x0)
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:310 +0xc8
gopkg.in/urfave/cli%2ev1.HandleAction(0x1406b60, 0x16a5728, 0xc0000e4000, 0xc000312d20, 0x0)
        /go-ethereum/build/_workspace/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000a0000, 0xc000032140, 0x14, 0x14, 0x0, 0x0)
        /go-ethereum/build/_workspace/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x58c
main.main()
        /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/main.go:250 +0x55
```
### System information
```
Geth
Version: 1.9.12-stable
Git Commit: b6f1c8dcc058a936955eb8e5766e2962218924bc
Architecture: amd64
Protocol Versions: [65 64 63]
Go Version: go1.13.8
Operating System: linux
GOPATH=/home/j/go
GOROOT=/build/ethereum-YoJS3q/.go
```

**Comment by nategraf** [comment] 2020-04-24 01:12
Weird, so for some reason `header` on this line myst be `nil`, which is odd because the canonical hash check above should have caught this 🤔 
https://github.com/celo-org/celo-blockchain/blob/dee2db520e239e50b9c0edbcae8d2e6fafd7d489/core/genesis.go#L177

**Comment by hbandura** [comment] 2020-12-15 20:36
Closing this issue since I can't reproduce it with the current baklava image.

**Closed by hbandura** 2020-12-15 20:36 UTC
Labels: blockchain, dev-support
